### ISSUE TITLE
Some question about Layernorm and GroupNorm.

### ISSUE THREAD

**Issue by Yangr116** [sail-sg/poolformer#11] opened 2021-12-02 10:35 UTC
Thanks for your good work in the CV area.
I have some questions about GroupNorm and LayerNorm.  The GroupNorm with group_num = 1 is equivalent to the LayerNorm. Why does GroupNorm outperform LayerNorm in your ablation study (Table. 6)?

A simple example from https://pytorch.org/docs/stable/generated/torch.nn.GroupNorm.html

input = torch.randn(20, 6, 10, 10)
\# Separate 6 channels into 3 groups
m = nn.GroupNorm(3, 6)
\# Separate 6 channels into 6 groups (equivalent with InstanceNorm)
m = nn.GroupNorm(6, 6)
\# **Put all 6 channels into a single group (equivalent with LayerNorm)**
m = nn.GroupNorm(1, 6)
\# Activating the module
output = m(input)

Looking forward to your reply!

**Comment by yuweihao** [comment] 2021-12-02 10:57
Hi @Yangr116 , this is a small mistake in the PyTorch GroupNorm API explanation. I have reported it to PyTorch. This issue is duplicated to issue #9 where I have given some explanation. Hope this can help you to understand it.

**Comment by yuweihao** [comment] 2021-12-02 10:57
Duplicate of #9

**Comment by Yangr116** [comment] 2021-12-02 11:03
Thanks for your quickly reply!



---Original---
From: "Weihao ***@***.***&gt;
Date: Thu, Dec 2, 2021 18:57 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [sail-sg/poolformer] Some question about Layernorm and GroupNorm. (Issue #11)




 
Duplicate of #9
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Closed** 2021-12-02 11:29 UTC
