### ISSUE TITLE
What is the difference between GN with group= 1 and LN?

### ISSUE THREAD

**Issue by ShihuaHuang95** [sail-sg/poolformer#17] opened 2021-12-19 04:45 UTC
Hi, could you please identify the difference between GN with group=1 and LN? The accuracy gap is large.

**Comment by yuweihao** [comment] 2021-12-20 05:25
Hi @ShihuaHuang95 , please the issue #9 .

**Comment by yuweihao** [comment] 2021-12-20 05:26
Duplicate of #9 .

**Closed by yuweihao** 2021-12-20 05:26 UTC
